let consts = {
    '1': {
        title: "Realtor as a specialist in buying / selling homes",
        text: "<p>Our Real Estate Agency invites the cooperation of realtors, home purchase and sale specialists and rental houses.</p><p>Collaboration with us is a teamwork, where everyone has the opportunity to get internships with the best specialists of the company, sign contracts during the internship period and earn money. Realtor revenue is a percentage of the cost of the company services.</p><p>Successful realtor will be a candidate:</p><ul><li>With higher, incomplete higher, secondary specialized education;</li><li>Inclined to business, gambling at work;</li><li>Ready to take on new knowledge;</li><li>Communicable;</li><li>Focused more on creative than routine activities;</li><li>Focuses on good earnings.</li></ul><p>If you have sufficient life and professional experience, you seek the recognition you need and are not afraid to start over, we are waiting for you at our company.</p><p>Additional information can be obtained by phone: +380 (44) 354 25 97, +380 (50) 420 58 31, +380 (67) 332 89 56, or by filling out a special form on our site.</p><span>CV with the job title should be sent to: </span><a href='#'>tornhill1997@gmail.com</a>"
    },
    '2': {
        title: "Specialist in buying / selling real estate",
        text: "<p>Collaboration with our company gives you the opportunity to study and learn real estate technology, get legal knowledge, improve negotiation skills and work with clients.</p><span>We offer:</span><ul><li>Mastering the prestigious profession of realtor;</li><li>Work in constant contact with high-level specialists;</li><li>Individual tutor support during the training and internship phase;</li><li>Decent payment on the results of signed contracts;</li><li>Great opportunities for career and professional growth.</li></ul><span>Our advantages:</span><ul><li>Successful work history of the company;</li><li>Use of the latest technologies in work;</li><li>Ready to take on new knowledge;</li><li>Strong legal service, complete documentation;</li>Respectable offices in the center of Vinnytsia.</ul><span>Requirements for candidates:</span><ul><li>Active life position;</li><li>Computer knowledge;</li><li>Ability to communicate;</li><li>Presentable appearance;</li><li>Goodwill;</li><li>Desire to work and earn;</li><li>Knowledge of a foreign language will be an additional advantage.</li></ul><p>For those wishing to get more information about our company and finally decide on cooperation, we arrange interviews.</p><p>Additional information can be obtained by phone: +380 (44) 354 25 97, +380 (50) 420 58 31, +380 (67) 332 89 56, or by filling out a <a href='#'>special form</a> on our site.</p><span>CV with the job title should be sent to: </span><a href='#'>tornhill1997@gmail.com</a>"
    },
    '3': {
        title: "Commercial real estate specialist",
        text: "<p>According to the development of the area we offer cooperation in the field of commercial real estate operations.</p><p>Our activity is services in buying / selling commercial premises of the capital. Many years of experience provide professionals who work with us tangible benefits.</p><span>Namely:</span><ul><li>The most complete database of metropolitan real estate, which is constantly updated;</li><li>Comprehensive legal support;</li><li>Active advertising promotion;</li><li>Modern vocational training;</li><li>Encouragement to new career goals.</li></ul><p>Our real estate agencies have the opportunity to undergo internships, enter into contracts, earn commissions and receive company income bonuses.</p><p>The professional level of our specialists deserves the trust of clients, generates significant income and generates social recognition.</p><p>Those looking for a promising job in today's market environment are welcome for individual interviews.</p><p>For those wishing to get more information about our company and finally decide on cooperation, we arrange interviews.</p><p>Additional information can be obtained by phone: +380 (44) 354 25 97, +380 (50) 420 58 31, +380 (67) 332 89 56, or by filling out a <a href='#'>special form</a> on our site.</p><span>CV with the job title should be sent to: </span><a href='#'>tornhill1997@gmail.com</a>"
    }
}


export default consts;